spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mdsvr3
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: testpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

# actuator
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
  endpoint:
    health:
      enabled: true
      show-details: always

migration:
  source-root-path: C:\Users\GMD_SOFT\Desktop
  target-root-path: D:\