spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mdsvr3
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: postgres
    password: testpassword
  jpa:
    hibernate:
      ddl-auto: validate

# actuator
management:
  endpoints:
    web:
      exposure:
        exclude: "health"
  endpoint:
    health:
      enabled: true
      show-details: always