spring:
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# actuator
management:
  server:
    port: 8081
